[log]
level = "debug"

[shared]
gatewaysvc = "your.revad.com:19000"

[grpc]
address = "0.0.0.0:19000"

[grpc.services.gateway]
authregistrysvc = "your.revad.com:19000"
appprovidersvc = "your.revad.com:19000"
appregistry = "your.revad.com:19000"
storageregistrysvc = "your.revad.com:19000"
preferencessvc = "your.revad.com:19000"
userprovidersvc = "your.revad.com:19000"
usershareprovidersvc = "your.revad.com:19000"
publicshareprovidersvc = "your.revad.com:19000"
ocmcoresvc = "your.revad.com:19000"
ocmshareprovidersvc = "your.revad.com:19000"
ocminvitemanagersvc = "your.revad.com:19000"
ocmproviderauthorizersvc = "your.revad.com:19000"
commit_share_to_storage_grant = false
datagateway = "https://your.revad.com/data"
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "your.revad.com:19000"
ocmshares = "your.revad.com:19001"
machine = "your.revad.com:19030"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = {"address" = "your.revad.com:19000"}
"/ocm" = {"address" = "your.revad.com:19001"}
"00000000-0000-0000-0000-000000000000" = {"address" = "your.revad.com:19000"}

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "nextcloud"

[grpc.services.ocmcore.drivers.nextcloud]
webdav_host = "https://your.efss.com/"
endpoint = "https://your.efss.com/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.ocminvitemanager]
driver = "json"
provider_domain = "your.revad.com"

[grpc.services.ocmshareprovider]
driver = "nextcloud"
provider_domain = "your.revad.com"
webdav_endpoint = "https://your.efss.com/"

[grpc.services.ocmshareprovider.drivers.nextcloud]
webdav_host = "https://your.efss.com/"
endpoint = "https://your.efss.com/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.ocmproviderauthorizer]
driver = "mentix"

[grpc.services.ocmproviderauthorizer.drivers.mentix]
url = "https://iop.sciencemesh.uni-muenster.de/iop/mentix/cs3"
verify_request_hostname = true
insecure = false
timeout = 10
refresh = 900

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.appprovider]
driver = "demo"
iopsecret = "testsecret"
wopiurl = "http://0.0.0.0:8880/"
wopibridgeurl = "http://localhost:8000/wopib"

[grpc.services.appregistry]
driver = "static"

[grpc.services.appregistry.static.rules]
"text/plain" = "your.revad.com:19000"
"text/markdown" = "your.revad.com:19000"
"application/compressed-markdown" = "your.revad.com:19000"
"application/vnd.oasis.opendocument.text" = "your.revad.com:19000"
"application/vnd.oasis.opendocument.spreadsheet" = "your.revad.com:19000"
"application/vnd.oasis.opendocument.presentation" = "your.revad.com:19000"

[grpc.services.storageprovider]
driver = "nextcloud"
expose_data_server = true
data_server_url = "https://your.revad.com/data"
enable_home_creation = true

[grpc.services.storageprovider.drivers.nextcloud]
endpoint = "https://your.efss.com/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.authprovider]
auth_manager = "nextcloud"

[grpc.services.authprovider.auth_managers.nextcloud]
endpoint = "https://your.efss.com/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[grpc.services.userprovider]
driver = "nextcloud"

[grpc.services.userprovider.drivers.nextcloud]
endpoint = "https://your.efss.com/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[http]
address = "0.0.0.0:443"
certfile = "/etc/revad/tls/revanc1.crt"
keyfile = "/etc/revad/tls/revanc1.key"

[http.services.sciencemesh]
invite_link_template = "{{.MeshDirectoryURL}}?token={{.Token}}&providerDomain=your.revad.com"
provider_domain = "your.revad.com"
mesh_directory_url = "https://sciencemesh.cesnet.cz/iop/meshdir"

[http.services.dataprovider]
driver = "nextcloud"

[http.services.prometheus]
[http.services.sysinfo]

[http.services.dataprovider.drivers.nextcloud]
endpoint = "https://your.efss.com/index.php/apps/sciencemesh/"
shared_secret = "shared-secret-1"
mock_http = false

[http.services.ocmprovider]
ocm_prefix = "ocm"
provider = "your.revad.com"
endpoint = "https://your.revad.com"
enable_webapp = true
enable_datatx = true

[http.services.ocmd]
prefix = "ocm"

[http.services.ocmd.config]
host = "your.revad.com"

[http.services.ocs]
prefix = "ocs"

[http.services.ocdav]
[http.middlewares.cors]
[http.middlewares.providerauthorizer]
driver = "mentix"

[http.middlewares.providerauthorizer.drivers.mentix]
url = "https://iop.sciencemesh.uni-muenster.de/iop/mentix/cs3"
verify_request_hostname = true
insecure = false
timeout = 10
refresh = 900
