[shared]
gatewaysvc = "localhost:19000"

[grpc]
address = "0.0.0.0:19030"

[grpc.services.authprovider]
auth_manager = "machine"

[grpc.services.authprovider.auth_managers.machine]
api_key = "machine-api-key"
gateway_addr = "localhost:19000"
